apiVersion: v1
kind: ConfigMap
metadata:
  name: smarter-device-manager-rpi
data:
  conf.yaml: |
        - devicematch: ^snd$
          nummaxdevices: 20
        - devicematch: ^gpiomem$
          nummaxdevices: 40
        - devicematch: ^gpiochip[0-9]*$
          nummaxdevices: 20
        - devicematch: ^hci[0-9]*$
          nummaxdevices: 1
        - devicematch: ^i2c-[0-9]*$
          nummaxdevices: 1
        - devicematch: ^rtc0$
          nummaxdevices: 20
        - devicematch: ^video[0-9]*$
          nummaxdevices: 20
        - devicematch: ^vchiq$
          nummaxdevices: 20
        - devicematch: ^vcsm.*$
          nummaxdevices: 20
