apiVersion: v2
name: smarter-device-manager
description: smarter-device-manager chart for SMARTER edge devices
home: https://github.com/smarter-device-manager
version: 0.0.5
appVersion: v1.20.11
kubeVersion: ">=1.16.0-0"
keywords:
  - kubernetes
  - device
  - hardware
sources:
  - https://github.com/smarter-project/smarter-device-manager

annotations:
  artifacthub.io/changes: |
    - Fix template
    - Add annotations
  artifacthub.io/license: Apache-2.0
  artifacthub.io/maintainers: |
    - name: Alexandre Ferreira
      email: alexandref75@gmail.com
  artifacthub.io/prerelease: "false"
  artifacthub.io/signKey: |
    fingerprint: 71EDA4E3D652DC73EB09E3A5387D298C169CF24E
    url: https://smarter-project.github.io/documentation/pgp_keys.asc
